@startuml
left to right direction

actor Guest
actor Trainer

rectangle "Fitness Class Management System" {

  usecase "View Class List" as UC1
  usecase "Book Class" as UC2
  usecase "Create Class" as UC3
  usecase "View Booking List" as UC4
}

actor Member
actor Admin

' Left side actors
Guest --> UC1
Trainer --> UC1

Trainer --> UC3
Trainer --> UC4

' Right side actors (reverse arrow)
UC1 <-- Member
UC2 <-- Member
UC1 <-- Admin

UC3 <-- Admin
UC4 <-- Admin

@enduml
